# **THEORITICAL QUESTIONS**

Ques 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?


Ans. 
    NumPy (Numerical Python) is a library for working with arrays and mathematical operations in Python. Its primary purpose is to provide support for large, multi-dimensional arrays and matrices, along with a wide range of high-performance mathematical functions to manipulate them.

    Application in scientific computing and data analysis:
    
    1. Scientific simulations (e.g., climate modeling, fluid dynamics)
    2. Data analysis (e.g., genomics, finance)
    3. Machine learning (e.g., neural networks, natural language processing)
    4. Image and signal processing

    Enhancing Python's Capabilities:

    1. Numerical Operations: NumPy provides optimized functions for numerical computations.
    2. Array Operations: Supports multi-dimensional array operations.
    3. Matrix Operations: Provides efficient matrix multiplication and other operations.
    4. Statistical Analysis: Offers functions for statistical analysis and data visualization.
    5. Data Analysis: Enables efficient data manipulation and analysis.

Ques 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Ans 
    difference:
            np.average() allows specifying weights for each element, whereas np.mean() does not.
            np.average() can calculate the average along a specified axis, whereas np.mean() can also do this, but with slightly different syntax.
            np.mean() always returns a scalar or an array of scalars, whereas np.average() returns a scalar or an array of scalars, or a weighted average.

    Usage:

        1. np.mean():
            - When you need a simple, unweighted mean.
            - When working with arrays without missing values.
            - For most general-purpose mean calculations.
        2. np.average()*:
            - When you need to specify weights for each element.
            - When working with arrays containing missing values (use weights argument).
            - For more complex averaging calculations.


Ques 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans 3
    1. np.flip(): Reverses the entire array.
    2. np.flipud(): Reverses the array along the 0th axis (up-down).
    3. np.fliplr(): Reverses the array along the 1st axis (left-right).
    4. arr[::-1]: Reverses the array using slicing.

In [1]:
import numpy as np
# 1D example:
arr = np.array([1, 2, 3, 4, 5])

reversed_arr = np.flip(arr)
print(reversed_arr)

[5 4 3 2 1]


In [2]:
#2D example:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

reversed_arr = np.flipud(arr)
print(reversed_arr)  

[[4 5 6]
 [1 2 3]]


Ques 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.


Ans 4
    1. np.dtype() function
    2. arr.dtype attribute
    3. np.type()
    
    Data types play a crucial role in:
     
    - Efficient memory allocation: NumPy arrays store elements of the same data type, reducing memory overhead.
    - Optimized operations: NumPy's vectorized operations are optimized for specific data types.
    - Predictable behavior: Data types ensure consistent behavior across different platforms.
    - Error prevention: Helps catch type-related errors at runtime.



Ques 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans 5
     In NumPy, an ndarray (N-dimensional array) is a multi-dimensional collection of values of the same data type stored in a contiguous block of memory.
    
    Key Features:

    1. Homogeneous: All elements have the same data type.
    2. Multi-dimensional: Supports 1D, 2D, 3D, and higher-dimensional arrays.
    3. Contiguous memory: Efficient memory allocation and access.
    4. Vectorized operations: Perform operations on entire arrays at once.
    5. Broadcasting: Automatically aligns arrays for operations.

    The NumPy ndarray uses less memory and provides faster computation than the Python list. However, the Python list offers more flexibility in terms of data type and dynamic resizing.

Ques 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.


Ans 6
    NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to vectorized operations, contiguous memory allocation, compiled C code, and parallelization capabilities.

Ques 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Ans 7 
    Key Differences


    1. Orientation: np.vstack() stacks arrays vertically, while np.hstack() stacks arrays horizontally.
    2. Input Arrays: Both functions accept tuples of arrays as input.
    3. Output Array: The output array's shape depends on the stacking orientation.

In [3]:
#vstack example

import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

vstacked_array = np.vstack((array1, array2))

print(vstacked_array)

[[1 2 3]
 [4 5 6]]


In [4]:
#hstack example
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Horizontally stack the arrays
hstacked_array = np.hstack((array1, array2))

print(hstacked_array)


[1 2 3 4 5 6]


Ques 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans 8
    np.fliplr()

    - Flips the array horizontally (left-right).
    - Reverses the order of columns.
    - Axis=1 (default).


    np.flipud()

    - Flips the array vertically (up-down).
    - Reverses the order of rows.
    - Axis=0 (default).

    np.fliplr()- No effect in 1D array ,Flips columns in 2D array ,Flips 2nd dimension (columns) in 3D array
    np.flipud()- Reverses elements in 1D, Flips rows in 2D , Flips 1st dimension (rows) in 3D 

Ques 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans 9
    np.array_split() is a NumPy method that splits an array into multiple sub-arrays along a specified axis.

    If the array length is (Uneven) not exactly divisible by num, np.array_split() will:
    
    1. Divide the array into num-1 equal-sized sub-arrays.
    2. Assign the remaining elements to the last sub-array.



Ques 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans 10
    Vectorization-Vectorization refers to performing operations on entire arrays at once, without the need for loops. NumPy's vectorized operations:

    1. Operate element-wise on arrays.
    2. Eliminate the need for explicit loops.
    3. Provide significant performance improvements.

    Broadcasting-Broadcasting allows NumPy to perform operations on arrays with different shapes and sizes. Broadcasting:

    1. Aligns arrays by adding dimensions (if necessary).
    2. Enables operations between arrays with different shapes.

    Contributution in efficient array operations
    
    1. Speed: Vectorization and broadcasting eliminate loops, making operations faster.
    2. Memory Efficiency: Broadcasting reduces memory allocation and copying.
    3. Expressiveness: Vectorization and broadcasting enable concise, readable code.
    4. Flexibility: Broadcasting allows operations between arrays with different shapes.


# **PRACTICAL QUESTIONS**

Ques 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


In [5]:
import numpy as np
a=np.random.randint(1,100,(3,3))
print(a)
print(a.T)

[[81 28 55]
 [48 49 75]
 [19  3 37]]
[[81 48 19]
 [28 49  3]
 [55 75 37]]


Ques 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


In [6]:
import numpy as np

arr = np.arange(10)
print(arr,"\n")

arr_2x5 = arr.reshape(2, 5)
print(arr_2x5,"\n")


arr_5x2 = arr.reshape(5, 2)
print(arr_5x2)

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Ques 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.





In [7]:
import numpy as np

arr = np.random.rand(4, 4)
zero_arr = np.zeros((6, 6))
zero_arr[1:5, 1:5] = arr
print(zero_arr)


[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.77257858 0.21045507 0.26182501 0.20943936 0.        ]
 [0.         0.05256273 0.49173543 0.47435049 0.91896149 0.        ]
 [0.         0.11709966 0.05266462 0.5750765  0.78761136 0.        ]
 [0.         0.00596113 0.12209184 0.91431918 0.26343804 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Ques 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.




In [8]:
np.arange(10, 61, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

Ques 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.




In [9]:
np.array(['python', 'numpy', 'pandas'])
arr1=np.char.upper(['python', 'numpy', 'pandas'])
arr2=np.char.lower(['python', 'numpy', 'pandas'])
arr3=np.char.title(['python', 'numpy', 'pandas'])
print(arr1,"\n",arr2,"\n",arr3)

['PYTHON' 'NUMPY' 'PANDAS'] 
 ['python' 'numpy' 'pandas'] 
 ['Python' 'Numpy' 'Pandas']


Ques 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.



In [10]:
np.char.join(' ', ['my', 'name', 'is','Vishesh'])

array(['m y', 'n a m e', 'i s', 'V i s h e s h'], dtype='<U13')


Ques 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.




In [11]:
arr4=np.array([[1,2,3],[4,5,6]])
arr5=np.array([[7,8,9],[10,11,12]])
print(arr4,"\n\n",arr5,"\n")
print("Sum of array",np.add(arr4,arr5))
print("subtraction of array",np.subtract(arr4,arr5))
print("multiplication of array",np.multiply(arr4,arr5))
print("division of array",np.divide(arr4,arr5))

[[1 2 3]
 [4 5 6]] 

 [[ 7  8  9]
 [10 11 12]] 

Sum of array [[ 8 10 12]
 [14 16 18]]
subtraction of array [[-6 -6 -6]
 [-6 -6 -6]]
multiplication of array [[ 7 16 27]
 [40 55 72]]
division of array [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Ques 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.




In [12]:
print(np.eye(5, dtype=int),"\n")
print("diagonal elements :",np.diag(np.eye(5,dtype=int)))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] 

diagonal elements : [1 1 1 1 1]


Ques 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.




In [13]:
arr6=np.random.randint(0,1000,100)
arr6.sort()
print(arr6)
print("\nprime no present in array:")

for i in arr6:
    if i < 2:
        continue
    for j in range(2,i):
        if i%j==0:
            break
    else:
       print(i ,end=" ")

[ 11  22  22  35  43  44  57  96 149 153 159 170 172 178 179 187 188 191
 205 214 214 221 221 225 237 238 259 261 262 276 286 292 294 306 307 312
 318 331 347 358 367 383 403 407 416 417 431 433 435 455 476 513 516 533
 540 542 560 560 577 577 582 590 595 611 611 614 660 663 663 663 675 715
 720 726 739 745 751 755 764 771 775 789 799 820 822 825 835 848 852 865
 881 883 926 934 942 949 965 975 987 993]

prime no present in array:
11 43 149 179 191 307 331 347 367 383 431 433 577 577 739 751 881 883 

Ques 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.


In [14]:
arr9=np.random.randint(0,40,30)
print(arr9,"\n")
print(arr9[0:7])
print("first week avg. :",np.mean(arr9[0:7]))
print(arr9[7:14])
print("second week avg.",np.mean(arr9[7:14]))
print(arr9[14:21])
print("third week avg.",np.mean(arr9[14:21]))
print(arr9[21:28])
print("fourth week avg.",np.mean(arr9[21:28],dtype=int),"°C")

[ 0  7  9  9 10 12  4 14 18 26 35 20  3 13 39  5 29 11  8  0 38 10  4 33
 38  9 22 36 20 37] 

[ 0  7  9  9 10 12  4]
first week avg. : 7.285714285714286
[14 18 26 35 20  3 13]
second week avg. 18.428571428571427
[39  5 29 11  8  0 38]
third week avg. 18.571428571428573
[10  4 33 38  9 22 36]
fourth week avg. 21 °C
